### PR TITLE
Fix classes being skipped when contain only @media

### LINKED ISSUE #41: Some classes being skipped when contain only @media
Hi and thank you for such a useful plugin!

Recently I noticed that some `.d.ts` files are missing few classes, particulary those which are consists only of @media query:

```css
.input {
  @media (min-width: 768px) {
    max-width: 370px;
  }
}
```

I can open PR with fix if you like

### PR DESCRIPTION
**Pull request by Nodman**
fixes #41 

* correct spelling splitted -> split
* add CSSJSObj type

### CODE REVIEW

File: src/extract.ts [hunk 1]
```diff
@@ -1,32 +1,38 @@
...
       }
 
       if (typeof value === 'object' && Object.keys(value).length > 0) {
-        const map = extractClassNameKeys(value, toParseCase)
+        const valueToExtract = Array.isArray(value)
+          ? collectionToObj(value)
+          : value
+        const map = extractClassNameKeys(valueToExtract, toParseCase)
         for (const key of map.keys()) {
-          if (key.startsWith('.')) {
```
Comment (Nodman) [inline src/extract.ts:24]: I removed this if condition because `map` already contains keys without `.`

**Comment by activeguild** [comment]
@Nodman 

Amazing!! Thanks!!!
